import './globals.css';
import { Inter } from 'next/font/google';
import { Provider } from './provider';
import GeminiChat from '@/components/GeminiChat';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '10k Steps',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
          <GeminiChat />
        </Provider>
      </body>
    </html>
  );
}
